---
- name: deploy the war file from to target tomcat server
  hosts: tomcat
  become: true
  vars:
    warfolder: "/opt/playbooks/artifacts-from-jenkins/Vinay*.war"
  tasks:

  - name: Display paths of all .war files in dir
    debug: msg={{ lookup('fileglob', "{{warfolder}}") }}

  - copy:
     src: "{{ item }}"
     dest: /opt/apache-tomcat-9.0.38/webapps
    with_fileglob:
     - "{{warfolder}}"
...
